# Copia questi valori nei Secrets di Streamlit Cloud.
# NON inserire mai password reali in GitHub.

AIRTABLE_TOKEN = ""
AIRTABLE_BASE_ID = "appoNJtS64JIcZUhT"
GOOGLE_OAUTH_TOKEN_JSON = ""
GOOGLE_DRIVE_FOLDER_ID = ""

ARUBA_D_DANGELO_EMAIL = "d.dangelo@financeplus.tech"
ARUBA_D_DANGELO_PASSWORD = ""

ARUBA_PRATICHE_EMAIL = "pratiche@financeplus.tech"
ARUBA_PRATICHE_PASSWORD = ""
